
[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd   = ['Denite', 'DeniteBufferDir', 'DeniteCursorWord']
on_func  = ['denite#']

hook_add = '''
autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> <CR>
  \ denite#do_map('do_action')
  nnoremap <silent><buffer><expr> d
  \ denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> p
  \ denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> q
  \ denite#do_map('quit')
  nnoremap <silent><buffer><expr> i
  \ denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> <Space>
  \ denite#do_map('toggle_select').'j'
endfunction
'''

hook_source = '''
source ~/.config/nvim/rc.d/rc_denite.vim
'''

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
depends = ['async.vim', 'deoplete-vim-lsp']
on_ft = ['c', 'cpp', 'python', 'prust', 'vue', 'go', 'typescript']
hook_add = '''
source ~/.config/nvim/rc.d/rc_vim-lsp.vim
'''

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'
depends = ['deoplete.nvim', 'vim-lsp']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_event = 'InsertEnter'
hook_source = '''
source ~/.config/nvim/rc.d/rc_deoplete.vim
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'vue', 'javascript']
hook_add = '''
let g:user_emmet_settings = {
\    'variables' : {
\        'lang' : 'ja',
\    }
\ }
'''

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

hook_add = '''
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_toc_autofit = 1
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'sakhnik/nvim-gdb'
build = 'bash install.sh'
on_ft = ['c', 'cpp', 'python']

[[plugins]]
repo = 'ozelentok/denite-gtags'
on_ft = ['c', 'cpp', 'python']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]    
repo = 'plasticboy/vim-markdown'    
on_ft = 'markdown'    
hook_add = '''    
let g:vim_markdown_folding_disabled = 1    
'''    

[[plugins]]    
repo = 'godlygeek/tabular'    
on_ft = 'markdown' 
