[[plugins]]
#repo = 'Shougo/ddu.vim'
repo = '~/ghq/github.com/shun/ddu.vim/'
depends = 'denops.vim'

[plugins.ftplugin]
ddu-std = '''
nnoremap <buffer><silent> <CR> <Cmd>call ddu#ui#std#do_action('default')<CR>
'''
