
[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'

hook_add = '''
'''

hook_source = '''
source ~/.config/nvim/rc.d/rc_denite.vim
'''

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
depends = 'deoplete.nvim'
on_ft = ['c', 'cpp', 'python', 'prust', 'vue', 'go']
build = 'bash install.sh'
hook_add = '''
set hidden
let g:LanguageClient_serverCommands = {
    \ 'c': ['clangd'],
    \ 'cpp': ['clangd'],
    \ 'python': ['pyls'],
    \ 'vue': ['vls'],
    \ 'rust': ['rustup', 'run', 'nightly', 'rls'],
    \ 'go': ['golsp']
    \ }
let g:LanguageClient_autoStart = 1
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_event = 'InsertEnter'
hook_source = '''
source ~/.config/nvim/rc.d/rc_deoplete.vim
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'vue', 'javascript']
hook_add = '''
let g:user_emmet_settings = {
\    'variables' : {
\        'lang' : 'ja',
\    }
\ }
'''

[[plugins]]
repo = 'w0rp/ale'
on_event = 'InsertEnter'
hook_add = '''
'''

hook_source = '''
source ~/.config/nvim/rc.d/rc_ale.vim
'''

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

hook_add = '''
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_toc_autofit = 1
'''
