[[plugins]]
repo = 'Shougo/dein.vim'
rtp = ''

[[plugins]]
repo = 'vim-scripts/gtags.vim'
hook_add = '''
'''

[[plugins]]
repo = 'Shougo/deol.nvim'
on_source = 'denite.nvim'
hook_add = '''
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
source ~/.config/nvim/rc.d/rc_ale.vim
'''

hook_source = '''
'''

[[plugins]]
repo = 'mhinz/neovim-remote'
hook_add = '''
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_i = 1
hook_add = '''
source ~/.config/nvim/rc.d/rc_deoplete.vim
'''

#[[plugins]]
#repo = 'Shougo/deoplete-lsp.nvim'
#on_i = 1
#hook_add = '''
#'''

[[plugins]]
repo = 'tpope/vim-markdown'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['vuejs', 'js', 'javascript']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
source ~/.config/nvim/rc.d/rc_lightline.vim
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'

hook_add = '''
'''

hook_post_source = '''
source ~/.config/nvim/rc.d/rc_denite.vim
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
source ~/.config/nvim/rc.d/rc_indentLine.vim
'''

[[plugins]]
repo = 'kassio/neoterm'
hook_add = '''
source ~/.config/nvim/rc.d/rc_neoterm.vim
'''

[[plugins]]
repo = 'aklt/plantuml-syntax'
hook_add = '''
source ~/.config/nvim/rc.d/rc_plantuml.vim
'''

[[plugins]]
repo = 'kannokanno/previm'
hook_add = '''
source ~/.config/nvim/rc.d/rc_previm.vim
'''
on_ft = 'markdown'

[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
let g:user_emmet_settings = {
\    'variables' : {
\        'lang' : 'ja',
\    }
\ }
'''

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'jsfaint/gen_tags.vim'
hook_add = '''
    let g:gen_tags#gtags_auto_gen = 1
'''

[[plugins]]
repo ='justinmk/vim-dirvish'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
depends = 'deoplete.nvim'
on_ft = ['c', 'cpp', 'python', 'prust', 'vue', 'go']
build = 'bash install.sh'
hook_add = '''
set hidden
let g:LanguageClient_serverCommands = {
    \ 'c': ['clangd'],
    \ 'cpp': ['clangd'],
    \ 'python': ['pyls'],
    \ 'vue': ['vls'],
    \ 'rust': ['rustup', 'run', 'nightly', 'rls'],
    \ 'go': ['golsp']
    \ }
let g:LanguageClient_autoStart = 1
'''

