[[plugins]]
repo = 'Shougo/dein.vim'
rtp = ''

[[plugins]]
repo ='justinmk/vim-dirvish'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
source ~/.config/nvim/rc.d/rc_lightline.vim
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
let g:indentLine_char = '|'
let g:indentLine_fileType = ['cpp', 'c', 'go', 'python', 'text', 'sh']
let g:indentLine_color_term = 239
'''

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
source ~/.config/nvim/rc.d/rc_ale.vim
'''

hook_source = '''
'''

[[plugins]]
repo='junegunn/vim-easy-align'
hook_add = '''
xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)
'''

[[plugins]]
repo='ghifarit53/tokyonight-vim'
hook_add = '''
set termguicolors

let g:tokyonight_style = 'storm' " available: night, storm
let g:tokyonight_enable_italic = 1

colorscheme tokyonight
'''
