[[plugins]]
repo = 'Shougo/dein.vim'
rtp = ''

[[plugins]]
repo='ghifarit53/tokyonight-vim'
hook_add = '''
set termguicolors

let g:tokyonight_style = 'storm' " available: night, storm
let g:tokyonight_enable_italic = 1
let g:tokyonight_menu_selection_background = 'blue'

colorscheme tokyonight
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
source ~/.config/nvim/rc.d/rc_lightline.vim
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
let g:indentLine_char = '|'
let g:indentLine_fileType = ['cpp', 'c', 'go', 'python', 'text', 'sh', 'typescript', 'typescriptreact']
let g:indentLine_color_term = 239
'''

[[plugins]]
repo='vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'
hook_source = '''
let g:context_filetype#ignore_patterns = {
    \ 'toml': ['^\s*#\s*'],
    \ }
'''

[[plugins]]
repo = 'gamoutatsumi/dps-ghosttext.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'tyru/caw.vim'

#[[plugins]]
#repo = 'kuuote/denops-skkeleton.vim'
#hook_source = '''
#    call skkeleton#register_kanatable('rom', {
#          \ 'hh': ['お', 'h'],
#          \ 'jj': 'escape',
#          \ 'z,': ['―', ''],
#          \ "z\<Space>": ["\u3000", ''],
#          \ })
#'''
#hook_add = '''
#    imap <C-j> <Plug>(skkeleton-toggle)
#    cmap <C-j> <Plug>(skkeleton-toggle)
#'''
#hook_source = '''
#call skkeleton#config(#{
#      \ globalJisyo: expand('~/.skk-jisyo'),
#      \ eggLikeNewline: v:true,
#      \ })
#'''
