[[plugins]]
repo = 'prabirshrestha/vim-lsp'
depends = ['vim-lsp-settings', 'ddc-vim-lsp']
on_ft = ['c', 'cpp', 'python', 'php', 'vue', 'go', 'typescript', 'typescriptreact', 'dockerfile', 'rust', 'javascript', 'html', 'xml', 'yaml', 'css']
hook_add = '''
"source ~/.config/nvim/rc.d/rc_vim-lsp.vim
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
on_ft = ['c', 'cpp', 'python', 'php', 'vue', 'go', 'typescript', 'typescriptreact', 'dockerfile', 'rust', 'javascript', 'html', 'xml', 'yaml', 'css']
hook_source = '''
'''
[[plugins]]
repo = 'mattn/vim-sonictemplate'
on_ft = ['c', 'cpp', 'markdown', 'python', 'php', 'vue', 'go', 'typescript', 'typescriptreact', 'dockerfile', 'rust', 'javascript', 'html', 'yaml']
hook_source = '''
source ~/.config/nvim/rc.d/rc_sonictemplate.vim
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd   = ['Denite', 'DeniteBufferDir', 'DeniteCursorWord']
on_func  = ['denite#']

hook_add = '''
autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> <CR>
  \ denite#do_map('do_action')
  nnoremap <silent><buffer><expr> d
  \ denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> p
  \ denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> q
  \ denite#do_map('quit')
  nnoremap <silent><buffer><expr> i
  \ denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> <Space>
  \ denite#do_map('toggle_select').'j'
endfunction
'''

hook_source = '''
source ~/.config/nvim/rc.d/rc_denite.vim
'''

#[[plugins]]
#repo = 'lambdalisue/gin.vim'
#on_cmd = ['GinStatus']
#
#[[plugins]]
#repo = 'lambdalisue/guise.vim'
#on_cmd = ['GinStatus']
#
