[[plugins]]
repo = 'Shougo/dein.vim'
rtp = ''

[[plugins]]
repo ='justinmk/vim-dirvish'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
source ~/.config/nvim/rc.d/rc_lightline.vim
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
let g:indentLine_char = '|'
let g:indentLine_fileType = ['cpp', 'c', 'go', 'python', 'text', 'sh']
let g:indentLine_color_term = 239
'''
