[[plugins]]
repo = 'Shougo/dein.vim'
rtp = ''

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'vim-scripts/gtags.vim'
hook_add = '''
'''

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
hook_add = 'nnoremap <silent>   [Space]v   :<C-u>VimFiler -invisible<CR>'
hook_source = '''
call vimfiler#custom#profile('default', 'context', {
      \ 'safe' : 0,
      \ 'auto_expand' : 1,
      \ 'parent' : 0,
      \ })
let g:vimfiler_as_default_explorer = 1
" Like Textmate icons.
let g:vimfiler_tree_leaf_icon = ' '
let g:vimfiler_tree_opened_icon = '▾'
let g:vimfiler_tree_closed_icon = '▸'
let g:vimfiler_file_icon = ' '
let g:vimfiler_readonly_file_icon = '✗'
let g:vimfiler_marked_file_icon = '✓'
'''

[[plugins]]
repo = 'Shougo/deol.nvim'
on_source = 'denite.nvim'
hook_add = '''
'''
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''

'''

hook_source = '''

'''

[[plugins]]
repo = 'ozelentok/denite-gtags'

[[plugins]]
repo = 'mhinz/neovim-remote'
hook_add = '''
'''

[[plugins]]
repo = 'zchee/deoplete-clang'
on_i = 1
on_ft = [ 'c', 'cpp']

[[plugins]]
repo = 'zchee/deoplete-go'
on_i = 1
on_ft = 'go'
build = 'make'

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_i = 1

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_i = 1
hook_add = '''
source ~/.config/nvim/rc/rc_deoplete.vim
'''

[[plugins]]
repo = 'tpope/vim-markdown'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
source ~/.config/nvim/plugins/mymolokai.vim
'''
[[plugins]]
repo = 'itchyny/vim-gitbranch'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
source ~/.config/nvim/rc/rc_quickrun.vim
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_add = '''
call denite#custom#map('insert', '<C-n>', '<denite:move_to_next_line>', 'noremap')
call denite#custom#map('insert', '<C-p>', '<denite:move_to_previous_line>', 'noremap')

nnoremap <silent> <Space>m :<C-u>Denite -mode=normal file_mru<CR>
nnoremap <silent> <Space>r :<C-u>Denite -mode=normal file_rec<CR>
nnoremap <silent> <Space>l :<C-u>Denite -mode=normal line<CR>
nnoremap <silent> <Space>b :<C-u>Denite -mode=normal buffer<CR>
nnoremap <silent> <Space>g :<C-u>Denite -mode=normal grep<CR>
nnoremap <silent> / :<C-u>Denite -buffer-name=search -auto-highlight -smartcase line<CR>
nnoremap <silent> * :<C-u>DeniteCursorWord -buffer-name=search -auto-highlight -mode=normal -smartcase line<CR>
nnoremap <silent> n :<C-u>Denite -buffer-name=search -resume -mode=normal -refresh<CR>

nnoremap sd :DeniteCursorWord -buffer-name=gtags_def gtags_def<cr>
nnoremap sr :DeniteCursorWord -buffer-name=gtags_ref gtags_ref<cr>
nnoremap sg :DeniteCursorWord -buffer-name=gtags_grep gtags_grep<cr>
nnoremap sc :Denite -buffer-name=gtags_completion gtags_completion<cr>
nnoremap sf :Denite -buffer-name=gtags_file gtags_file<cr>
nnoremap sp :Denite -buffer-name=gtags_path gtags_path<cr>

vnoremap sd :Denite -cursor-pos=0 -buffer-name=gtags_def gtags_def<cr>
vnoremap sr :Denite -cursor-pos=0 -buffer-name=gtags_ref gtags_ref<cr>
vnoremap sg :Denite -cursor-pos=0 -buffer-name=gtags_grep gtags_grep<cr>
vnoremap sc :Denite -buffer-name=gtags_completion gtags_completion<cr>
vnoremap sf :Denite -buffer-name=gtags_file gtags_file<cr>
vnoremap sp :Denite -buffer-name=gtags_path gtags_path<cr>

nnoremap sD :Denite -resume -mode=normal -refresh -buffer-name=gtags_def gtags_def<cr>
nnoremap sR :Denite -resume -mode=normal -refresh -buffer-name=gtags_ref gtags_ref<cr>
nnoremap sG :Denite -resume -mode=normal -refresh -buffer-name=gtags_grep gtags_grep<cr>
nnoremap sC :Denite -resume -mode=normal -refresh -buffer-name=gtags_completion gtags_completion<cr>
nnoremap sF :Denite -resume -mode=normal -refresh -buffer-name=gtags_file gtags_file<cr>
nnoremap sP :Denite -resume -mode=normal -refresh -buffer-name=gtags_path gtags_path<cr>

'''

hook_post_source = '''
source ~/.config/nvim/rc/rc_denite.vim
'''

[[plugins]]
repo = 'tomasr/molokai'

# complete
#[[plugins]]
#repo = 'Shougo/neocomplete.vim'
#depends    = ['Shougo/neoinclude.vim', 'Shougo/context_filetype.vim']
#on_i = 1
#hook_add = '''
#let g:neocomplete#enable_at_startup = 1
#
#if !exists('g:neocomplete#force_omni_input_patterns')
#  let g:neocomplete#force_omni_input_patterns = {} 
#endif
#let g:neocomplete#force_overwrite_completefunc = 1
#let g:neocomplete#force_omni_input_patterns.c =
#      \ '[^.[:digit:] *\t]\%(\.\|->\)\w*'
#let g:neocomplete#force_omni_input_patterns.cpp =
#      \ '[^.[:digit:] *\t]\%(\.\|->\)\w*\|\h\w*::\w*'
#'''

#[[plugins]]
#repo = 'vim-syntastic/syntastic'
#hook_add = '''
#let g:syntastic_go_checkers = ['golint', 'gotype', 'govet', 'go']
#'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
source ~/.config/nvim/rc/rc_indentLine.vim
'''
# golang
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
'''

[[plugins]]
repo = 'kassio/neoterm'
hook_add = '''
source ~/.config/nvim/rc/rc_neoterm.vim
'''

[[plugins]]
repo = 'zchee/nvim-go'
build = 'make'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'
on_ft = 'rust'
hook_source = '''
'''

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_add = '''
let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'aklt/plantuml-syntax'
hook_add = '''
source ~/.config/nvim/rc/rc_plantuml.vim
'''

[[plugins]]
repo = 'mhartington/nvim-typescript'
on_ft = 'typescript'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'artur-shaik/vim-javacomplete2'
on_ft = 'java'

[[plugins]]
repo = 'kannokanno/previm'
hook_add = '''
source ~/.config/nvim/rc/rc_previm.vim
'''
on_ft = 'markdown'

